### ISSUE TITLE
Minimal Merge roadmap

### ISSUE THREAD

**Issue by tersec** [status-im/nim-beacon-chain#2859]
M0 through M5 milestones defined at https://hackmd.io/@tvanepps/amphora-milestones

- [x] guide https://github.com/status-im/nimbus-eth2/pull/2858 into `unstable`, creating base from which multiple people can work
- [x] implement other beacon chain merge functions, largely back-end computational logic (including upgrade_to_merge)
- [x] add tests as they pass to the tested part of the EF test suite, taking advantage of support for running with/without execution client to do so without devops changes initially
- [x] audit all `ALTAIR_FORK_EPOCH` references to ensure they behave properly with respect to `MERGE_FORK_EPOCH`
- [x] add merge block/state database support, including immutable-state support, along with tests
- [x] add merge hardfork usage to `block_sim`
- [x] implement modified BeaconBlocksByRange v2 / BeaconBlocksByRoot v2
- [x] subscribe/unsubscribe to/from merge topics
- [x] recreate or port over https://github.com/status-im/nimbus-eth2/pull/2477 from `quick-merge-v1` branch the RPC mechanisms such that they target current (similar, but tweaked) protocol
- [x] M0 milestone
- [x] M1 milestone
- [x] create working launch_local_testnet support for at least post-merge world and ideally merge itself
- [x] document, along the lines of https://github.com/status-im/nimbus-eth2/blob/stable/docs/rayonism_merge.md, how to run this testnet with geth or other execution client- [ ] implement modified beacon_block gossip validation (https://github.com/ethereum/consensus-specs/blob/v1.1.0/specs/merge/p2p-interface.md#beacon_block)- [ ] M2 milestone
- [x] M2 milestone
- [x] M3 milestone
- [x] M4 milestone
- [ ] M5 milestone

**Comment by tersec** [comment]
M5 is effectively separate -- it's a whole-ecosystem effort more intrinsically.
