### ISSUE TITLE
Implement EIP-4844 

### ISSUE THREAD

**Issue by henridf** [status-im/nim-beacon-chain#4395]
# Tracking issue for EIP-4844 tasks

### Config & Setup
   - [x] New containers ([beacon block](https://github.com/ethereum/consensus-specs/blob/dev/specs/eip4844/beacon-chain.md#beaconblockbody), [execution payload](https://github.com/ethereum/consensus-specs/blob/dev/specs/eip4844/beacon-chain.md#executionpayload)) (#4365)
   - [x] New [constants](https://github.com/ethereum/consensus-specs/blob/dev/specs/eip4844/beacon-chain.md#constants) and [presets](https://github.com/ethereum/consensus-specs/blob/dev/specs/eip4844/beacon-chain.md#preset). (#4365)

### State transition & processing
- [x] [Block processing](https://github.com/ethereum/consensus-specs/blob/dev/specs/eip4844/beacon-chain.md#beacon-chain-state-transition-function) 
   - [x] Move is_data_available check to fork-choice on_block (https://github.com/ethereum/consensus-specs/pull/3185)
- [x] Nim bindings to [`c-kzg-4844`](https://github.com/ethereum/c-kzg-4844) library. _(in progress https://github.com/henridf/nim-kzg-4844)_
- [x] Support [trusted setup](https://github.com/ethereum/consensus-specs/blob/dev/specs/eip4844/polynomial-commitments.md#trusted-setup) loading.

### P2P
- Gossip processing
   - [x] Gossip transition. (https://github.com/status-im/nimbus-eth2/pull/4463)
   - [x] [`beacon_block_and_blobs_sidecar`](https://github.com/ethereum/consensus-specs/blob/dev/specs/eip4844/p2p-interface.md#beacon_block_and_blobs_sidecar) new topic. #4444
      - [x] `beacon_block_and_blobs_sidecar` validation
- ReqResp processing
   - [x] [`BeaconBlocksByRange v2`](https://github.com/ethereum/consensus-specs/blob/dev/specs/eip4844/p2p-interface.md#beaconblocksbyrange-v2)
   - [x] [`BeaconBlocksByRoot v2`](https://github.com/ethereum/consensus-specs/blob/dev/specs/eip4844/p2p-interface.md#beaconblocksbyroot-v2)
   - [x] [`BeaconBlockAndBlobsSidecarByRoot v1`](https://github.com/ethereum/consensus-specs/blob/dev/specs/eip4844/p2p-interface.md#beaconblockandblobssidecarbyroot-v1) __(in progress #4475)__
   - [x] [`BlobsSidecarsByRange v1`](https://github.com/ethereum/consensus-specs/blob/dev/specs/eip4844/p2p-interface.md#blobssidecarsbyrange-v1)  (https://github.com/status-im/nimbus-eth2/pull/4464)

### Storage
- [x] Read and write blobs _(https://github.com/status-im/nimbus-eth2/pull/4454)_
  - [x] Refactor per discussion at https://github.com/status-im/nimbus-eth2/pull/4454#issuecomment-1375505802 (in progress #4491)
- [x] Pruning of blobs past [`MIN_EPOCHS_FOR_BLOBS_SIDECARS_REQUESTS`](https://github.com/ethereum/consensus-specs/blob/dev/specs/eip4844/p2p-interface.md#configuration) epochs. #5283 

### Sync
- [x] Gossip sync (#4527)
- [x] Backfill sync (#4581)

Also, keep in mind following two notes from [eip4844. BlobsSidecarsByRange](https://github.com/ethereum/consensus-specs/blob/v1.3.0-alpha.2/specs/eip4844/p2p-interface.md#blobssidecarsbyrange-v1):
> Note: The above requirement implies that nodes that start from a recent weak subjectivity checkpoint MUST backfill the local blobs database to at least epoch current_epoch - MIN_EPOCHS_FOR_BLOBS_SIDECARS_REQUESTS to be fully compliant with BlobsSidecarsByRange requests.
> Note: Although clients that bootstrap from a weak subjectivity checkpoint can begin participating in the networking immediately, other peers MAY disconnect and/or temporarily ban such an un-synced or semi-synced client.

### Validator duties
- [x] [Block and Sidecar proposal](https://github.com/ethereum/consensus-specs/blob/dev/specs/eip4844/validator.md#block-and-sidecar-proposal)

### Testing
- [x] EF Test vectors (#4431, #4399, and some other PRs)
- [x] Run in local testnet (in progress)

**Comment by henridf** [comment]
This is done (and in part outdated, as is from before the blob/block decoupling spec changes).
