### ISSUE TITLE
dencun-devnet-8 specs (4844-related list)

### ISSUE THREAD

**Issue by henridf** [status-im/nim-beacon-chain#5185]
https://notes.ethereum.org/@ethpandaops/dencun-devnet-8

Note that this issue is focused on 4844, but devnet-8 has more than that.

- [x] [Move EIP-4788 to Deneb](https://github.com/ethereum/consensus-specs/pull/3421)  (done in #5147)
- [x] [Cancun specification](https://github.com/ethereum/execution-apis/pull/420) (done in #5147)
- [x] [Engine API: employ one method one structure approach for V3](https://github.com/ethereum/execution-apis/pull/418) (no PR, we seem to be already doing this)
- [x] [PR-317 - Add broadcast_validation to block publishing](https://github.com/ethereum/beacon-APIs/pull/317) (partially done in #5214)
- [x] Starting from devnet-9 we will be starting from Capella at epoch 0. Please make sure your client is able to handle genesis time == shanghai time, and capella_fork_epoch = 0
- [x] [Rename "data gas" to "blob gas"](https://github.com/ethereum/consensus-specs/pull/3461)

EL-only, for reference:
- [Add dataGasUsed and dataGasPrice to receipts for 4844 txs](https://github.com/ethereum/execution-apis/pull/398)

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/5214 has been merged, so this is complete.
