### ISSUE TITLE
Discv5 Improvements

### ISSUE THREAD

**Issue by kdeme** [status-im/nim-beacon-chain#848]
Improvements / bugfixes / features that are most important for nbc, in order of priority:
- [x] Make sure FindNode works properly: https://github.com/status-im/nim-eth/issues/205
- [x] Passing ENR custom fields: needed for https://github.com/ethereum/eth2.0-specs/blob/v0.11.1/specs/phase0/p2p-interface.md#eth2-field , see also https://github.com/status-im/nim-beacon-chain/issues/832. 
- [x] Filtering discovered nodes based on ENR custom fields: needed for https://github.com/ethereum/eth2.0-specs/blob/v0.11.1/specs/phase0/p2p-interface.md#eth2-field , see also https://github.com/status-im/nim-beacon-chain/issues/832. Without this one we will still possible try to dial with a node that is not useful.
- [x] Fix error handling: https://github.com/status-im/nim-eth/issues/185
- [x] Checks on AuthResponse: https://github.com/status-im/nim-eth/issues/204
- [x] Liveness functionality: https://github.com/status-im/nim-eth/issues/183
- [x] Better (re)validation: https://github.com/status-im/nim-eth/issues/206
- [x] Allow to update ENR: https://github.com/status-im/nim-eth/issues/208

Tests:
- [ ] More tests, e.g.: https://github.com/status-im/nim-eth/issues/181

**Comment by kdeme** [comment]
Decided to change focus more on https://github.com/status-im/nim-eth/issues/185 and work on #183 and #206 at later time

**Comment by kdeme** [comment]
So, this item can be moved to next May milestones. 
Initial focus was shifted from adding features to first work on the error handling. Some ground work was done there (https://github.com/status-im/nim-eth/pull/231) but more is to be done.

**Comment by kdeme** [comment]
I'd close this instead of move as the last item is handled here: https://github.com/status-im/nim-eth/pull/266
And while not all tests mentioned in that test item are handled, several other (not mentioned are). 
So probably better to create a new item with which discovery items to handle.
